from datetime import datetime


class EmailGenerator:

    def generate(self, metadata: dict):

        doc_type = metadata.get("document_type")
        recipient = metadata.get("recipient") or "legal-team@company.test"

        subject = f"New {doc_type} Received – Action Required"

        body = f"""
Dear Legal Team,

A new {doc_type} has been processed by the AI document handling system.

Extracted Metadata:
----------------------------------------
Document Type: {metadata.get("document_type")}
Date of Loss: {metadata.get("date_of_loss")}
Policy Number: {metadata.get("policy_number")}
Recipient: {metadata.get("recipient")}
Claimant: {metadata.get("claimant")}
Defendant: {metadata.get("defendant")}
Case Reference: {metadata.get("case_reference")}
Policy Variant Count: {metadata.get("policy_variant_count")}
Policy Inconsistency: {metadata.get("policy_inconsistency")}
Confidence Score: {metadata.get("confidence_score")}
----------------------------------------

Please review the extracted information and validate before taking further action.

This email was auto-generated by the AI-enabled Service of Suits prototype.

Timestamp: {datetime.utcnow().isoformat()} UTC

Kind regards,
AI Document Processing System
"""

        return {
            "recipient": recipient,
            "subject": subject,
            "body": body.strip()
        }